@startuml Login Functionality

actor User
participant "Login\nController" as Controller
participant "Authentication\nService" as AuthService
database "User\nRepository" as UserRepo

User -> Controller: Credentials
Controller -> AuthService: Redirect Crendetials

alt Valid credentials

    AuthService -> Controller: Authorized
    Controller -> UserRepo: User registered?

    alt Register user

        UserRepo -> Controller: Yes
        Controller -> UserRepo: Save user

    else Increment visit counter

        UserRepo -> Controller: No
        Controller -> UserRepo: Increment visit counter

    end

    Controller -> Controller: Generate token
    Controller -> User: Token

else Invalid credentials

    AuthService -> Controller : Unauthorized
    Controller -> User: Bad Request

end

@enduml
