@startuml Lost Items Functionality

actor User
participant "Lost Items\nController" as Controller
database "User\nRepository" as UserRepo
database "Lost Items\n Repository" as LostRepo

User -> Controller: Token
Controller -> UserRepo: User registered?

alt Username registered

    UserRepo -> Controller: Yes
    Controller -> LostRepo: Get lost items
    LostRepo -> Controller: Lost items
    Controller -> User: Lost items

else Username not registered

    UserRepo -> Controller: No
    Controller -> User: Unauthorized

end

@enduml
